package com.pi.picodingreadjson.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class BreedsModel {
    public List<String> wolfhound;
    public List<String> whippet;
    public List<String> weimaraner;
    public List<String> waterdog;
    public List<String> vizsla;
    public List<String> terrier;
    public List<String> stbernard;
    public List<String> springer;
    public List<String> spaniel;
    public List<String> shihtzu;
    public List<String> shiba;
    public List<String> sheepdog;
    public List<String> setter;
    public List<String> schnauzer;
    public List<String> schipperke;
    public List<String> samoyed;
    public List<String> saluki;
    public List<String> rottweiler;
    public List<String> ridgeback;
    public List<String> retriever;
    public List<String> redbone;
    public List<String> pyrenees;
    public List<String> puggle;
    public List<String> pug;
    public List<String> poodle;
    public List<String> pomeranian;
    public List<String> pointer;
    public List<String> pitbull;
    public List<String> pinscher;
    public List<String> pembroke;
    public List<String> pekinese;
    public List<String> dhole;
    public List<String> deerhound;
    public List<String> dane;
    public List<String> dalmatian;
    public List<String> dachshund;
    public List<String> cotondetulear;
    public List<String> corgi;
    public List<String> coonhound;
    public List<String> collie;
    public List<String> cockapoo;
    public List<String> clumber;
    public List<String> chow;
    public List<String> chihuahua;
    public List<String> cattledog;
    public List<String> cairn;
    public List<String> bullterrier;
    public List<String> beagle;
    public List<String> basenji;
    public List<String> australian;
    public List<String> appenzeller;
    public List<String> akita;
    public List<String> airedale;
    public List<String> african;
    public List<String> affenpinscher;
    public List<String> bluetick;
    public List<String> borzoi;
    public List<String> bouvier;
    public List<String> boxer;
    public List<String> brabancon;
    public List<String> briard;
    public List<String> buhund;
    public List<String> bulldog;
    public List<String> dingo;
    public List<String> doberman;
    public List<String> elkhound;
    public List<String> entlebucher;
    public List<String> eskimo;
    public List<String> finnish;
    public List<String> frise;
    public List<String> germanshepherd;
    public List<String> greyhound;
    public List<String> groenendael;
    public List<String> havanese;
    public List<String> hound;
    public List<String> husky;
    public List<String> keeshond;
    public List<String> kelpie;
    public List<String> komondor;
    public List<String> kuvasz;
    public List<String> labradoodle;
    public List<String> labrador;
    public List<String> leonberg;
    public List<String> lhasa;
    public List<String> malamute;
    public List<String> malinois;
    public List<String> maltese;
    public List<String> mastiff;
    public List<String> mexicanhairless;
    public List<String> mix;
    public List<String> mountain;
    public List<String> newfoundland;
    public List<String> otterhound;
    public List<String> ovcharka;
    public List<String> papillon;
}
